apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorten
  labels:
    app: shorten
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shorten
  template:
    metadata:
      labels:
        app: shorten
    spec:
      containers:
        - name: shorten
          image: localhost:3000/manh/shorten-api:250203a
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: shorten
---
apiVersion: v1
kind: Service
metadata:
  name: shorten-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: shorten